 ALTER TABLE Query.IssueTypePageIssue DROP CONSTRAINT IIssueTypePageIssue_ProjectKey
 ALTER TABLE Query.IssueTypePageIssue DROP CONSTRAINT IssueTypePageIssue_ApplicationKey
 ALTER TABLE Query.IssueTypePageIssue DROP CONSTRAINT IssueTypePageIssue_VersionKey
 ALTER TABLE Query.IssueTypePageIssue DROP CONSTRAINT IssueTypePageIssue_IssueTypeKey
