CREATE UNIQUE NONCLUSTERED INDEX [Fingerprint] ON [dbo].[ApplicationUser]
(
	[Fingerprint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
UPDATE Machine SET Fingerprint = A.Fingerprint + '_' + CAST(A.MachineId AS varchar) FROM (SELECT * FROM Machine WHERE Fingerprint IN (SELECT Fingerprint FROM Machine GROUP BY Fingerprint HAVING COUNT(*) > 1)) AS A
GO
CREATE UNIQUE NONCLUSTERED INDEX [Fingerprint] ON [dbo].[Machine]
(
	[Fingerprint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
