CREATE TABLE Project (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	CreationDate DATETIME NOT NULL,
	LastUpdateDate DATETIME NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	DashboardColor NVARCHAR(20) NOT NULL,
	ClientToken NVARCHAR(50) NOT NULL,

);

GO

ALTER TABLE Project
ADD CONSTRAINT NO_DUP_TOKEN UNIQUE (ClientToken)