CREATE TABLE Application (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Project(Id),
	Name NVARCHAR(MAX) NOT NULL,
	CreationDate DATETIME NOT NULL,
	LastUpdateDate DATETIME NOT NULL,

);