CREATE TABLE dbo.CallLog
(
	CallLogId INT NOT NULL IDENTITY,
	CallKey UNIQUEIDENTIFIER NOT NULL,
	SessionKey VARCHAR(50) NULL,
	ProjectKey UNIQUEIDENTIFIER NULL,
	ServerTime DATETIME NOT NULL,
	ElapsedMilliseconds INT NOT NULL,
	CallerIp VARCHAR(45) NULL,
	UserName VARCHAR(50) NULL,
	RequestType VARCHAR(20) NOT NULL,
	CallPath VARCHAR(MAX) NOT NULL,
	Request VARCHAR(MAX) NOT NULL,
	Response VARCHAR(MAX) NULL,
	IssueKey UNIQUEIDENTIFIER NULL,
	CONSTRAINT PK_CallLog PRIMARY KEY CLUSTERED ( CallLogId )
)

