DROP TABLE CallLog
DROP TABLE IssueData
DROP TABLE MachineData
DROP TABLE ProjectInvitation
DROP TABLE ProjectTarget
DROP TABLE ProjectUser
--DROP TABLE Setting
--DROP TABLE UserRole
DROP TABLE [Query].[Issue]
DROP TABLE Issue
DROP TABLE IssueType
DROP TABLE IssueTypeDetail
--DROP TABLE [Role]
DROP TABLE [Session]
DROP TABLE [Version]
DROP TABLE [Application]
DROP TABLE ApplicationUser
DROP TABLE Machine
DROP TABLE Project
--DROP TABLE [User]