CREATE TABLE UserData (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Fingerprint NVARCHAR(MAX) NOT NULL,
	UserName NVARCHAR(MAX) NOT NULL,
	CreationDate DATETIME NOT NULL,
	LastUpdateDate DATETIME NOT NULL
);