CREATE TABLE IssueTypePageIssueType (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	ApplicationId UNIQUEIDENTIFIER NOT NULL,
	VersionId UNIQUEIDENTIFIER NOT NULL,
	ProjectName NVARCHAR(50) NOT NULL,
	ApplicationName NVARCHAR(MAX) NOT NULL,
	Version NVARCHAR(MAX) NOT NULL,
	Ticket INT NOT NULL,
	Type NVARCHAR(MAX) NOT NULL,
	Level NVARCHAR(50) NOT NULL,
	Message NVARCHAR(MAX) NULL,
	StackTrace NVARCHAR(MAX) NULL
);