<?xml version="1.0" encoding="utf-8"?><Database Name="Quilt4" Class="Quilt4DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Quilt4;Integrated Security=True" SettingsObjectName="Quilt4.Service.SqlRepository.Properties.Settings" SettingsPropertyName="Quilt4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Application" Member="Applications">
    <Type Name="Application">
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Application_Version" Member="Versions" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="Version" />
      <Association Name="Project_Application" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Version" Member="Versions">
    <Type Name="Version">
      <Column Name="VersionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VersionKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VersionNumber" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="BuildTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SupportToolkitVersion" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Version_Session" Member="Sessions" ThisKey="VersionId" OtherKey="VersionId" Type="Session" />
      <Association Name="Version_IssueType" Member="IssueTypes" ThisKey="VersionId" OtherKey="VersionId" Type="IssueType" />
      <Association Name="Application_Version" Member="Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationUser" Member="ApplicationUsers">
    <Type Name="ApplicationUser">
      <Column Name="ApplicationUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationUserKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fingerprint" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ApplicationUser_Session" Member="Sessions" ThisKey="ApplicationUserId" OtherKey="ApplicationUserId" Type="Session" />
      <Association Name="Project_ApplicationUser" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBVersion" Member="DBVersions">
    <Type Name="DBVersion">
      <Column Name="PatchName" Type="System.String" DbType="VarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatchTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VersionNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Checksum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IssueData" Member="IssueDatas">
    <Type Name="IssueData">
      <Column Name="IssueDataId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IssueId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Issue_IssueData" Member="Issue" ThisKey="IssueId" OtherKey="IssueId" Type="Issue" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Machine" Member="Machines">
    <Type Name="Machine">
      <Column Name="MachineId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MachineKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fingerprint" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Machine_MachineData" Member="MachineDatas" ThisKey="MachineId" OtherKey="MachineId" Type="MachineData" />
      <Association Name="Machine_Session" Member="Sessions" ThisKey="MachineId" OtherKey="MachineId" Type="Session" />
      <Association Name="Project_Machine" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MachineData" Member="MachineDatas">
    <Type Name="MachineData">
      <Column Name="MachineDataId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MachineId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Machine_MachineData" Member="Machine" ThisKey="MachineId" OtherKey="MachineId" Type="Machine" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Project" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DashboardColor" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectApiKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastTicket" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Project_Application" Member="Applications" ThisKey="ProjectId" OtherKey="ProjectId" Type="Application" />
      <Association Name="Project_ApplicationUser" Member="ApplicationUsers" ThisKey="ProjectId" OtherKey="ProjectId" Type="ApplicationUser" />
      <Association Name="Project_Machine" Member="Machines" ThisKey="ProjectId" OtherKey="ProjectId" Type="Machine" />
      <Association Name="Project_ProjectInvitation" Member="ProjectInvitations" ThisKey="ProjectId" OtherKey="ProjectId" Type="ProjectInvitation" />
      <Association Name="Project_ProjectUser" Member="ProjectUsers" ThisKey="ProjectId" OtherKey="ProjectId" Type="ProjectUser" />
      <Association Name="User_Project" Member="User" ThisKey="OwnerUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectInvitation" Member="ProjectInvitations">
    <Type Name="ProjectInvitation">
      <Column Name="ProjectInvitationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="InviterUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InviteCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServerCreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Project_ProjectInvitation" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
      <Association Name="User_ProjectInvitation" Member="User" ThisKey="InviterUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_ProjectInvitation1" Member="User1" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectUser" Member="ProjectUsers">
    <Type Name="ProjectUser">
      <Column Name="ProjectUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Project_ProjectUser" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
      <Association Name="User_ProjectUser" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Session" Member="Sessions">
    <Type Name="Session">
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartClientTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StartServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUsedServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndServerTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CallerIp" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Enviroment" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="MachineId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApplicationUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VersionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Session_Issue" Member="Issues" ThisKey="SessionId" OtherKey="SessionId" Type="Issue" />
      <Association Name="ApplicationUser_Session" Member="ApplicationUser" ThisKey="ApplicationUserId" OtherKey="ApplicationUserId" Type="ApplicationUser" IsForeignKey="true" />
      <Association Name="Machine_Session" Member="Machine" ThisKey="MachineId" OtherKey="MachineId" Type="Machine" IsForeignKey="true" />
      <Association Name="Version_Session" Member="Version" ThisKey="VersionId" OtherKey="VersionId" Type="Version" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Setting" Member="Settings">
    <Type Name="Setting">
      <Column Name="SettingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserRole" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserKey" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AvatarUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Project" Member="Projects" ThisKey="UserId" OtherKey="OwnerUserId" Type="Project" />
      <Association Name="User_ProjectInvitation" Member="ProjectInvitations" ThisKey="UserId" OtherKey="InviterUserId" Type="ProjectInvitation" />
      <Association Name="User_ProjectInvitation1" Member="ProjectInvitations1" ThisKey="UserId" OtherKey="UserId" Type="ProjectInvitation" />
      <Association Name="User_ProjectUser" Member="ProjectUsers" ThisKey="UserId" OtherKey="UserId" Type="ProjectUser" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="UserId" OtherKey="UserId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Issue" Member="Issues">
    <Type Name="Issue">
      <Column Name="IssueId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IssueKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IssueTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationClientTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IssueThreadKey" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Issue_IssueData" Member="IssueDatas" ThisKey="IssueId" OtherKey="IssueId" Type="IssueData" />
      <Association Name="Session_Issue" Member="Session" ThisKey="SessionId" OtherKey="SessionId" Type="Session" IsForeignKey="true" />
      <Association Name="IssueType_Issue" Member="IssueType" ThisKey="IssueTypeId" OtherKey="IssueTypeId" Type="IssueType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IssueTypeDetail" Member="IssueTypeDetails">
    <Type Name="IssueTypeDetail">
      <Column Name="IssueTypeDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentIssueTypeDetailId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StackTrace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(2048) NOT NULL" CanBeNull="false" />
      <Association Name="IssueTypeDetail_IssueTypeDetail" Member="IssueTypeDetails" ThisKey="IssueTypeDetailId" OtherKey="ParentIssueTypeDetailId" Type="IssueTypeDetail" />
      <Association Name="IssueTypeDetail_IssueType" Member="IssueTypes" ThisKey="IssueTypeDetailId" OtherKey="IssueTypeDetailId" Type="IssueType" />
      <Association Name="IssueTypeDetail_IssueTypeDetail" Member="IssueTypeDetail1" ThisKey="ParentIssueTypeDetailId" OtherKey="IssueTypeDetailId" Type="IssueTypeDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IssueType" Member="IssueTypes">
    <Type Name="IssueType">
      <Column Name="IssueTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IssueTypeKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VersionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ticket" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IssueTypeDetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="IssueType_Issue" Member="Issues" ThisKey="IssueTypeId" OtherKey="IssueTypeId" Type="Issue" />
      <Association Name="IssueTypeDetail_IssueType" Member="IssueTypeDetail" ThisKey="IssueTypeDetailId" OtherKey="IssueTypeDetailId" Type="IssueTypeDetail" IsForeignKey="true" />
      <Association Name="Version_IssueType" Member="Version" ThisKey="VersionId" OtherKey="VersionId" Type="Version" IsForeignKey="true" />
    </Type>
  </Table>
</Database>