<?xml version="1.0" encoding="utf-8"?><Database Name="Quilt4" Class="ReadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Quilt4;Integrated Security=True;Persist Security Info=False" SettingsObjectName="Quilt4.Service.SqlRepository.Properties.Settings" SettingsPropertyName="Quilt4ConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="Query.IssueRead" Member="IssueReads">
    <Type Name="IssueRead">
      <Column Name="IssueId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IssueKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ticket" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StackTrace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VersionNumber" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>