CREATE TABLE Version (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ApplicationId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Application(Id),
	Version NVARCHAR(MAX) NOT NULL,
	SupportToolkitVersion NVARCHAR(MAX) NOT NULL,
	CreationDate DATETIME NOT NULL,
	LastUpdateDate DATETIME NOT NULL,
);