CREATE TABLE IssueType (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	VersionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Version(Id),
	Type NVARCHAR(MAX) NOT NULL,
	Level NVARCHAR(50) NOT NULL,
	Message NVARCHAR(MAX) NULL,
	StackTrace NVARCHAR(MAX) NULL,
	Ticket INT NOT NULL,
	CreationDate DATETIME NOT NULL,
	LastUpdateDate DATETIME NOT NULL,
);