CREATE TABLE Session (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ClientStartTime DATETIME NOT NULL,
	ServerStartTime DATETIME NOT NULL,
	ClientEndTime DATETIME NULL,
	ServerEndTime DATETIME NULL,
	CallerIp NVARCHAR(45) NOT NULL,
);