CREATE TABLE VersionPageVersion (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	ApplicaitonId UNIQUEIDENTIFIER NOT NULL,
	ProjectName NVARCHAR(50) NOT NULL,
	ApplicationName NVARCHAR(MAX) NOT NULL,
	Version NVARCHAR(MAX) NOT NULL
);