CREATE TABLE VersionPageIssueType (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	ApplicationId UNIQUEIDENTIFIER NOT NULL,
	VersionId UNIQUEIDENTIFIER NOT NULL,
	Ticket INT NOT NULL DEFAULT 0,
	Type NVARCHAR(MAX) NOT NULL,
	Issues INT NOT NULL DEFAULT 0,
	Level NVARCHAR(50) NOT NULL,
	LastIssue DATETIME,
	Enviroments NVARCHAR(MAX) NOT NULL
);