CREATE TABLE IssueTypePageIssue (
	Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	ProjectId UNIQUEIDENTIFIER NOT NULL,
	ApplicationId UNIQUEIDENTIFIER NOT NULL,
	VersionId UNIQUEIDENTIFIER NOT NULL,
	IssueTypeId UNIQUEIDENTIFIER NOT NULL,
	Time DATETIME NOT NULL,
	IssueUser NVARCHAR(MAX) NULL,
	Enviroment NVARCHAR(200) NOT NULL,
	Data NVARCHAR(MAX) NULL

);